### ISSUE TITLE
error in prod env

### ISSUE THREAD

**Issue by RoopaJain** [basst314/ngx-webcam-demo#1]
Not able to build the code base in production environment, shows the following error 

**ERROR in Error during template compile of 'WebcamModule'
  Function calls are not supported in decorators but '?makeDecorator' was called
 in 'NgModule'
    'NgModule' calls '?makeDecorator'.**

When i run the angualr 5 project in dev mode, build is successful
but when i choose Prod mode command as "ng build --aot", the above error pops up in CLI.

**Comment by basst314** [comment]
Hi @RoopaJain,

please post all Issues in the [ngx-webcam](https://github.com/basst314/ngx-webcam) repository. I do not watch this repo, as it's only meant as documentation for showcasing the usage of ngx-webcam.

However, I just tried `ng build --aot` on this demo-project and another project using the library and it builds successfully.

Which version of ngx-webcam and Angular are you using? Can you try with the latest version of ngx-webcam?

Hope you are able to resolve the issue.

Cheers!

**Comment by basst314** [comment]
Hi @RoopaJain,
sorry, I just found this issue [in the other repo](https://github.com/basst314/ngx-webcam/issues/10). Will close it here and follow up on it at over there.
Thanks!
