### ISSUE TITLE
iOS support 

### ISSUE THREAD

**Issue by peeceebee** [basst314/ngx-webcam-demo#3]
Should the live demo work on my iPhone X? I’m getting a message “Cannot access media from User Device.” No prompt for permissions or camera access when I run the demo or press take picture.

**Comment by basst314** [comment]
Hi @peeceebee,
Yes it should work. I just tested again on my iPhone XS, running iOS 12.1.3.
Are you using the standard safari browser?

If you‘re using any other mobile browser please make sure it supports the necessary MediaDevices / userMedia APIs. Those are required to access your device‘s webcam.

Thanks

**Comment by peeceebee** [comment]
That is the issue. In Safari, it works fine. In Google Chrome on IOS, it throws the message above. The Chrome app settings have permission to use the Camera.  It appears that Chrome will not have access to webRTC and userMedia, only Safari. I can deal with that. 

Thanks for the support.

**Comment by basst314** [comment]
That may very well be the case. Hope they will add support for it soon.

Thanks for letting me know!

I‘ll close this issue, but if there‘s anything else please feel free to create a new one, preferably in the library project tracker.

Thanks!

**Comment by AlexisLapeze** [comment]
hi everyone, have you some news for chrome on ios ?

regards
