### ISSUE TITLE
Missing preffered facing mode

### ISSUE THREAD

**Issue by nirhu** [basst314/ngx-webcam-demo#5]
There is an option to select preffered facing mode in the Live-Demo. The code for it is missing here.

**Comment by basst314** [comment]
Hi @nirhu,

Thanks for raising this. This demo-repo is a little outdated. I should definitely clean this up.

However, you can find the relevant code in the original repo‘s app component:

https://github.com/basst314/ngx-webcam/blob/master/src/app/app.component.html

Hope that helps!
Cheers
